"""add type column to account table

Revision ID: e3f6fd3fea6b
Revises: 814f6d13ce38
Create Date: 2026-05-01 23:21:42.501769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f6fd3fea6b'
down_revision: Union[str, Sequence[str], None] = '814f6d13ce38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('type', sa.String(length=20), nullable=True, default='checking'))
    account_table = sa.sql.table('accounts', sa.sql.column('type', sa.String(length=20)))
    op.execute(account_table.update().values(type='checking'))
    op.alter_column('accounts', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'type')
    # ### end Alembic commands ###
