"""add type column

Revision ID: 35e85de9c43b
Revises: 345e004ec29a
Create Date: 2026-03-22 19:16:33.366429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35e85de9c43b'
down_revision: Union[str, Sequence[str], None] = '345e004ec29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('type', sa.String(length=20), nullable=True, default='checking'))
    account_table = sa.sql.table('accounts', sa.sql.column('type', sa.String(length=20)))
    op.execute(account_table.update().values(type='checking'))
    op.alter_column('accounts', 'type', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'type')
    # ### end Alembic commands ###
